### ISSUE TITLE
vv fails to build with InsightToolkit-5.2.1: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'const itk::ImageIOBase::IOByteOrderEnum'

### ISSUE THREAD

**Issue by yurivict** [open-vv/vv#96]
@tbaudier :

```
/disk-samsung/freebsd-ports/graphics/vv/work/vv-1.4.0-383-g7a783a8b/common/rtkEdfImageIO.cxx:167:30: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'const itk::ImageIOBase::IOByteOrderEnum' (aka 'const itk::CommonEnums::IOByteOrder')
          { "LowByteFirst",  LittleEndian }, /* little endian */
                             ^~~~~~~~~~~~
/disk-samsung/freebsd-ports/graphics/vv/work/vv-1.4.0-383-g7a783a8b/common/rtkEdfImageIO.cxx:168:30: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'const itk::ImageIOBase::IOByteOrderEnum' (aka 'const itk::CommonEnums::IOByteOrder')
          { "HighByteFirst", BigEndian },    /* big endian */
                             ^~~~~~~~~
/disk-samsung/freebsd-ports/graphics/vv/work/vv-1.4.0-383-g7a783a8b/common/rtkEdfImageIO.cxx:172:7: error: cannot initialize a variable of type 'int' with an lvalue of type 'const itk::ImageIOBase::IOByteOrderEnum' (aka 'const itk::CommonEnums::IOByteOrder')
  int byteorder = LittleEndian;
      ^           ~~~~~~~~~~~~
/disk-samsung/freebsd-ports/graphics/vv/work/vv-1.4.0-383-g7a783a8b/common/rtkEdfImageIO.cxx:178:19: error: invalid operands to binary expression ('int' and 'const itk::ImageIOBase::IOByteOrderEnum' (aka 'const itk::CommonEnums::IOByteOrder'))
      if(byteorder==LittleEndian)
         ~~~~~~~~~^ ~~~~~~~~~~~~
/usr/local/include/ITK-5.2/itkSmartPointer.h:223:1: note: candidate template ignored: could not match 'SmartPointer<T>' against 'int'
operator==(const SmartPointer<T> & l, const SmartPointer<TU> & r) noexcept
^
/usr/local/include/ITK-5.2/itkSmartPointer.h:229:1: note: candidate template ignored: could not match 'SmartPointer<T>' against 'int'
operator==(const SmartPointer<T> & l, std::nullptr_t) noexcept
^
```
