### ISSUE TITLE
fatal error: 'vtkOpenGLImageActor.h' file not found

### ISSUE THREAD

**Issue by yurivict** [open-vv/vv#93]
Fails to build with vtk-9.1:
```
/disk-samsung/freebsd-ports/graphics/vv/work/vv-1.4.0-397-ge2cfe654/vv/vvBlendImageActor.h:30:10: fatal error: 'vtkOpenGLImageActor.h' file not found
#include <vtkOpenGLImageActor.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

vtk-9.1 doesn't install this file.
